### ISSUE TITLE
이모지클릭시 에러 

### ISSUE THREAD

**Issue by Seungwoo321** [WilloughbyHarborHackathon/Naan#22]
![image](https://user-images.githubusercontent.com/13829929/31315681-27beb77e-ac58-11e7-981b-335787417f74.png)

**Comment by ruucm** [comment]
related_tracks.ts 에서 mappedTrackIds의 length를 고려하지 않고 

candidates를 구하려함

관련한 이슈 처리 [링크](https://github.com/WilloughbyHarborHackathon/Naan/commit/7cdcebe2d827cb6f6011b7eb70d9372113c278d4l)
