### ISSUE TITLE
날씨에 따른 weather 커버 부족

### ISSUE THREAD

**Issue by ruucm** [WilloughbyHarborHackathon/Naan#4]
현재 warm, fog, rainy, snowy에 대한 커버 이미지만 존재

**Comment by bookseob** [comment]
목금토일중으로 최대한 마무리 지어볼게요ㅎㅎ

**Comment by bookseob** [comment]
아 그리고 궁금한게 있는데.. 커버 이미지 뒤에 하얀 색 원이 생기는 거 없애주실 수 있나요?

**Comment by ruucm** [comment]
@bookseob 아 png파일이 아니여서 그랬던것 같아요. png파일로 새 디자인 이미지들 전달주시면 될듯 합니다!
