### ISSUE TITLE
어떤 감정이신가요?(이모지) 가운데 정렬 요망

### ISSUE THREAD

**Issue by bookseob** [WilloughbyHarborHackathon/Naan#5]
현재 왼쪽으로 패딩 값이 23정도 들어가 있는데 패딩값을 좀 줄여야 하지 않을까 싶네요^^
타이틀부터 이모지들까지 전체적으로 오른쪽으로 쏠려 있는 것 같습니다.

**Comment by ruucm** [comment]
@bookseob 그때 빨리하느라 그랬던것 같아요 ㅋㅋ 정렬 완료했습니다
