### ISSUE TITLE
날씨에서 온도 정보가 없음

### ISSUE THREAD

**Issue by ruucm** [WilloughbyHarborHackathon/Naan#6]

**Comment by ruucm** [comment]
@gyukebox 병규님 혹시 온도 불러오는거 가능하실까요?

**Comment by gyukebox** [comment]
@ruucm 넵 최대한 주말안으로 작업해서 올리겠습니당

**Comment by gyukebox** [comment]
@ruucm 넵 `gyu` 브랜치에 작업 완료해서 올렸습니다 머지해주세요!

**Comment by ruucm** [comment]
@gyukebox 앗 이슈처리 정말 감사드립니다! (제가 요즘 일때문에 지금 확인하네요 ㅠㅠ 죄송)
